stages:
  data_ingestion:
    cmd: python -m src.data.data_ingestion
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.random_state
    - data_ingestion.test_size
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
  preprocessing:
    cmd: python -m src.data.preprocessing
    deps:
    - src/data/preprocessing.py
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/interim/train.csv
    - data/interim/test.csv
